### ISSUE TITLE
build instruction does not work in docker-compose.yml

### ISSUE THREAD

**Issue by mchauvel** [qnap-dev/container-apps#47] opened 2017-09-23 17:06 UTC
When trying to make my own LAMP template, i try to replace 
``` image: php:7.1-apache```
by 
``` 
build: ./php
dockerfile: Dockerfile-php71
```
but i always have this error : **Background task error for application: 'image'**

the same docker-compose.yml works with command line (ssh on the NAS): ```docker-compose  up```

i've also tried with docker compose v2 without success :(

PS : is there a way to specify a dynamic name(via wizard?) in order to instanciate many times the same APP ? (```docker-compose -p DYN_NAME up```)

**Comment by fcwu** [comment] 2017-10-02 02:14
@e1ee1e11 

May you try to fix this that change `current working directory` to `application working directory`?

**Comment by e1ee1e11** [comment] 2017-10-17 10:25
[root cause]
CS only accept 'image' instruction in docker-compose.yml

[solution]
Accept 'build' instruction

[revision]
fixed in the next release version (CS v1.8)

**Closed as completed** 2017-10-17 10:26 UTC
